version: "3.7"

services:
#--------------------------------------------
 web:
  build:
   context: ./
   dockerfile: ./srcs/web/Dockerfile
  restart: on-failure
  
  command: bash -c "npm run dev"
  
  ports:
   - 3000:3000

  networks:
   - e2e_net

#--------------------------------------------
 styleguidist:
  build:
   context: ./
   dockerfile: ./srcs/styleguidist/Dockerfile
  restart: on-failure
  
  command: bash -c "npm run styleguide"


  ports:
   - 6060:6060

  networks:
   - e2e_net
   

#--------------------------------------------
 api:
  build:
   context: ./
   dockerfile: ./srcs/api/Dockerfile
  restart: on-failure
  
  command: bash -c "python manage.py runserver 0.0.0.0:8000"

      
  ports:
   - 8000:8000
      
  env_file:
   - .env
      
  networks:
   - e2e_net
   
  depends_on:
   - db

#--------------------------------------------
 db:
  image: postgres
  restart: on-failure
  
  volumes:
   - e2e-db:/var/lib/postgresql/data
      
  env_file:
   - .env
   
  networks:
   - e2e_net

networks:
 e2e_net:


volumes:
 e2e-db:
